---
title: "movie recommedation"
output: html_document
date: "2024-03-31"
---

```{r movielens}
library(tidyverse)
library(caret)

options(timeout = 120)

dl <- "ml-10M100K.zip"
if(!file.exists(dl))
  download.file("https://files.grouplens.org/datasets/movielens/ml-10m.zip", dl)

ratings_file <- "ml-10M100K/ratings.dat"
if(!file.exists(ratings_file))
  unzip(dl, ratings_file)

movies_file <- "ml-10M100K/movies.dat"
if(!file.exists(movies_file))
  unzip(dl, movies_file)
```

```{r movielens}
ratings <- as.data.frame(str_split(read_lines(ratings_file), fixed("::"), simplify = TRUE),
                         stringsAsFactors = FALSE)
colnames(ratings) <- c("userId", "movieId", "rating", "timestamp")
ratings <- ratings %>%
  mutate(userId = as.integer(userId),
         movieId = as.integer(movieId),
         rating = as.numeric(rating),
         timestamp = as.integer(timestamp))
```


```{r movielens}

movies <- as.data.frame(str_split(read_lines(movies_file), fixed("::"), simplify = TRUE),
                        stringsAsFactors = FALSE)
colnames(movies) <- c("movieId", "title", "genres")
movies <- movies %>%
  mutate(movieId = as.integer(movieId))


```


```{r movielens}
movielens <- left_join(ratings, movies, by = "movieId")
str(movielens)
head(movielens)

```
Final hold-out test set will be 10% of MovieLens data
```{r}
set.seed(1, sample.kind="Rounding")

test_index <- createDataPartition(y = movielens$rating, times = 1, p = 0.1, list = FALSE)
edx <- movielens[-test_index,]
temp <- movielens[test_index,]

#ensure userId and movieId in final hold-out test set are also in edx set
final_holdout_test <- temp %>% 
  semi_join(edx, by = "movieId") %>%
  semi_join(edx, by = "userId")

# Add rows removed from final hold-out test set back into edx set
removed <- anti_join(temp, final_holdout_test)
edx <- rbind(edx, removed)

rm(dl, ratings, movies, test_index, temp, movielens, removed)
```
the structure of edx dataset.

```{r}
str(edx)

```
visualization of the data 

```{r}
library(lubridate)
edx%>%mutate(year= as_datetime(timestamp,origin="1970-01-01"))%>%
  ggplot(aes(x=year))+geom_histogram(bins = 30)+ggtitle("Movie Rating Yearly")+xlab("Year")+ylab("No. of Rating")
```
TO clear explain the counts above 

```{r}

edx%>%mutate(date=date(as_datetime(timestamp,origin="1970-01-01")))%>%dplyr::group_by(title,date)%>%
  summarise(count=n())%>%arrange(-count)%>%head(10)
```
the counts for the ratings 

```{r}
edx%>%group_by(rating)%>%summarise(count=n())%>%head(10)
```
to visualize the table above
```{r}
edx%>%ggplot(aes(x=rating))+geom_bar()+ggtitle("Ratings Distribution")+xlab("Ratings")+ylab("Counts")

```
the movie distribution 
```{r}
edx%>%group_by(movieId)%>%summarise(n=n())%>%ggplot(aes(n))+
  geom_histogram()+scale_x_log10()+
  ggtitle("Movie Distribution")+xlab("MovieId")+ylab("Ratings")
```
movie distribution
```{r}
edx%>%group_by(movieId)%>%summarise(n=n())
```
the distribution of movies and rating using the heatmap
```{r}
users<-sample(unique(edx$userId),100)
edx%>%filter(userId%in%users)%>%
  select(userId,movieId,rating)%>%
  mutate(rating=1)%>%
  spread(movieId,rating)%>%select(sample(ncol(.),100))%>%as.matrix()%>%t(.)%>%
  image(1:100,1:100,.,xlab = "Movies",ylab = "Users")%>%abline(h=0:100+.5,v=0:100+.5)%>%title("User and movies matrix distribution")
```




